version: "3.9"
services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: pos_invoice
    ports:
      - "3306:3306" # kalau port 3306 sudah dipakai lokal, ganti kiri jadi 3307:3306
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
